[package]
name = "chat-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.12.1"
derive_builder = "0.12.0"
indxvec = "1.8.0"
log = "0.4.19"
tiktoken-rs = { version = "0.5.0", default-features = false, features = ["async-openai"] }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
